CREATE TABLE security_logs_raw (
                                   log_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                   event_time TIMESTAMPTZ NOT NULL,
                                   username VARCHAR(100),
                                   user_role VARCHAR(50),
                                   account_status VARCHAR(30),
                                   ip_address VARCHAR(50),
                                   port_number INT,
                                   device_type VARCHAR(50),
                                   operating_system VARCHAR(100),
                                   browser_name VARCHAR(100),
                                   location_city VARCHAR(100),
                                   location_region VARCHAR(100),
                                   location_country VARCHAR(100),
                                   event_type VARCHAR(100) NOT NULL,
                                   event_category VARCHAR(100),
                                   action_taken VARCHAR(100),
                                   status VARCHAR(50),
                                   severity VARCHAR(30),
                                   resource_type VARCHAR(100),
                                   resource_name VARCHAR(200),
                                   session_id VARCHAR(200),
                                   failure_reason VARCHAR(100),
                                   risk_score DECIMAL(4,2),
                                   watchlist_flag BOOLEAN,
                                   notes TEXT
);